import Head from 'next/head';
import Link from 'next/link';
import { getProjects } from '@/configuration/mdx-utils';
import ProjectCard from '@/components/projectCard';

export default function Home({ projects }) {
  return (
    <>
      <Head>
        <title>Michael du Toit</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <div className="landingSplash">
          <h2 className='header'>Michael du Toit</h2>
          <p className='downArrow'>&gt;</p>
        </div>
        <main>
          <section className='viewSection'>
            <h3>Hi! I'm Michael!</h3>
            <p>I am a Full Stack Developer who enjoys working across all technologies and platforms. Currently located in Wellington, New Zealand.<br/>         
            </p>
          </section>
          <section className='viewSection'>
            <h3 className='center-text'>Featured Projects:</h3>
            <ul className="projectCardContainer">
            {
                projects.sort((a, b) => orderProjects(a, b)).map((project) => (
                      <ProjectCard key={project.page}
                        url={`/projects/${project.page}`} 
                        title={project.title}
                        image=""
                        />
                ))
            }
            </ul>
            <Link href="/projects" className='center-text'>See More....</Link>
          </section>          
        </main>
      </div>
    </>
  )
}


export function getStaticProps()
{
    const projects = getProjects();

    return { props: { projects }}
}

export function orderProjects(a, b)
{
  let firstObjSortOrder = a.sortOrder != null ? a.sortOrder : 1000;
  let secondObjSortOrder = b.sortOrder != null ? b.sortOrder : 1000;

  // first we order by the SortOrder meta data.
  if(firstObjSortOrder < secondObjSortOrder)
  {
    return -1;
  }

  if(firstObjSortOrder > secondObjSortOrder)
  {
    return 1;
  }

  // if they have the same SortOrder, then sort alphabetically by the title
  let firstObjTitle = a.title != null ? a.title.toUpperCase() : "";
  let secondObjTitle = b.title != null ? b.title.toUpperCase() : "";

  if(firstObjTitle < secondObjTitle)
  {
    return -1;
  }

  if(firstObjTitle > secondObjTitle)
  {
    return 1;
  }

  return 0;
}